// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

const SUPABASE_URL = "https://hhhqfylcjzpgqrdxzfnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoaHFmeWxjanpwZ3FyZHh6Zm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzIyNDgsImV4cCI6MjA2NzY0ODI0OH0.abd5KhgEdGOzAyRj2eu2PiumRSEAWJGG7ScLPipupgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});